#ifndef drvIK320_ERR_STAT_h
#define drvIK320_ERR_STAT_h
/* This file was automatically generated by 'errScan' */
/* ---------------- DO NOT EDIT MANUALLY ------------ */

#include <errMdef.h>
void drvIK320RegErrStr(void);
#endif
