#!/bin/sh

# ensure that multiple, simultaneous IOCs are not started by this user ID

MY_UID=`id -u`
IOC_PID="`/usr/bin/pgrep xxx\$ -u ${MY_UID}`"

if [ "" != "${IOC_PID}" ] ; then
  echo "xxx IOC is already running, won't start a new one, PID=${IOC_PID}"
  exit 1
fi

# start the IOC

../../bin/${EPICS_HOST_ARCH}/xxx st.cmd
